@startuml
title DiagramTests - orders a bike
participant "customer"
participant "checkout-api"
participant "warehouse"
database "db"
participant "bank"
"customer" -> "checkout-api": POST bikes/{id}/order
activate "checkout-api"
"checkout-api" -> "warehouse": GET bikes/{id}
activate "warehouse"

"warehouse" -[#DarkGreen]> "checkout-api": <color:DarkGreen> 200 OK
deactivate "warehouse"
"checkout-api" <-> "db": find by user id
"checkout-api" -> "bank": POST finalize
activate "bank"

"bank" -[#DarkGreen]> "checkout-api": <color:DarkGreen> 200 OK
deactivate "bank"
"checkout-api" <-> "db": create order
"checkout-api" -[#DarkGreen]> "customer": <color:DarkGreen> 201 Created
deactivate "checkout-api"
@enduml